baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
exclude: [
  "node_modules",
  "webpack.config.js",
  "package.json",
  "README.md",
  "License",
  "npm-debug.log",
  "Gemfile",
  "Gemfile.lock",
  "package-lock.json",
  "src",
  ".idea",
  ".gitattributes",
  "_data/statistics/old"

]
include: [ "_pages" ]
plugins: [ rouge, jekyll-last-modified-at ]
keep_files: [ .git, .gitignore, CNAME ]
